import { SocialNetwork, SocialService } from 'common/constants';
import {
  MLDraftAudio,
  MLDraftButton,
  MLDraftCarousel,
  MLDraftDivider,
  MLDraftImage,
  MLDraftImageText,
  MLDraftLink,
  MLDraftLogo,
  MLDraftShop,
  MLDraftSocial,
  MLDraftText,
  MLDraftVideo,
  MLDraftVote,
  MLDraftWidget,
  Nullable,
  TIncomingImage,
} from 'common/types/instance';

const sliderImage1 = 'https://i.ibb.co/xq8q4H3/slider-Image1.png';
const sliderImage2 = 'https://i.ibb.co/8DWmTRm/slider-Image2.png';
const sliderImage3 = 'https://i.ibb.co/jLSDYmR/slider-Image3.png';

export const mlDrafts = [
  {
    background: '#fff',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 100,
        margin: [0],
      }),
      new MLDraftText({
        isFilled: true,
        text: 'Привет, меня зовут Евгений, и я готовлю к ЕГЭ и ОГЭ по математике более 10 лет',
        color: '#fff',
        font: '400 14px Inter, sans-serif',
        textAlign: 'left',
        margin: [0, 0, 24],
        padding: [24, 24],
        background: 'rgba(47, 58, 244, 0.73)',
      }),
      new MLDraftText({
        isFilled: true,
        text: 'ТОП БЕСПЛАТНЫХ КУРСОВ',
        color: '#fff',
        font: '700 20px Inter, sans-serif',
        textAlign: 'left',
        padding: [12, 24],
        margin: [0, 0, 12],
        background: 'rgba(47, 58, 244, 0.73)',
      }),
      new MLDraftVideo({
        isFilled: true,
        url: 'https://www.youtube.com/embed/hYu0d-4SX_Y',
        width: 327,
        height: 184,
        margin: [0, 0, 24],
        padding: [0, 24],
      }),
      new MLDraftText({
        isFilled: true,
        text: 'ТОП КУРСОВ',
        color: '#fff',
        font: '700 20px Inter, sans-serif',
        textAlign: 'left',
        padding: [12, 24],
        margin: [0, 0, 12],
        background: 'rgba(47, 58, 244, 0.73)',
      }),
      new MLDraftShop({
        isFilled: true,
        grid: '1fr 1fr 1fr',
        gap: 5,
        cells: [
          {
            order: 0,
            image: null,
            background: '#fff',
            title: 'Курс "ВСПОМНИТЬ ВСЁ" 2022 (повторение всех заданий ЕГЭ)',
            subtitle: '2 490 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 1,
            image: null,
            background: '#fff',
            title: 'Видеокурс 1-11 задания ЕГЭ 2022 профиль (первая часть с нуля)',
            subtitle: '990 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 2,
            image: null,
            background: '#fff',
            title:
              'Видеокурс 12 задания ЕГЭ 2022 профиль (тригонометрия и другие типы 12-х с нуля)',
            subtitle: '790 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 3,
            image: null,
            background: '#fff',
            title: 'Видеокурс 13 задания ЕГЭ 2022 профиль (стереометрия с нуля)',
            subtitle: '790 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 4,
            image: null,
            background: '#fff',
            title: 'Видеокурс 10 задания ЕГЭ 2022 профиль (неравенства с нуля)',
            subtitle: '790 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 5,
            image: null,
            background: '#fff',
            title: 'Видеокурс 16 задания ЕГЭ 2022 профиль (планиметрия с нуля)',
            subtitle: '990 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 6,
            image: null,
            background: '#fff',
            title: 'Видеокурс 15 задания ЕГЭ 2022 профиль (кредиты и другие виды 15-х с нуля)',
            subtitle: '790 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
          {
            order: 7,
            image: null,
            background: '#fff',
            title: 'Видеокурс 17 задания ЕГЭ 2022 профиль (параметры с нуля)',
            subtitle: '990 ₽',
            href: `${process.env.REACT_APP_HOST_PRODUCTION}/purchase?t=wwcs9v`,
          },
        ],
        color: '#000',
        font: '400 10px Inter, sans-serif',
        textAlign: 'left',
        subtitleColor: '#000',
        subtitleFont: '700 12px Inter, sans-serif',
        subtitleTextAlign: 'center',
        margin: [0, 0, 24],
        padding: [12, 24],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        href: 'https://www.youtube.com/c/pifagor1/live',
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [0, 0, 24],
        padding: [12, 48],
      }),
      new MLDraftSocial({
        isFilled: true,
        links: [
          'https://vk.com/shkolapifagora',
          'https://www.youtube.com/channel/UC7Z3j8Cgsa2NnBmKAl7uOuQ',
          'https://instagram.com/shkola_pifagora',
        ],
        linkTypes: [SocialNetwork.VK, SocialNetwork.YOUTUBE, SocialNetwork.INSTAGRAM],
        size: 75,
        margin: [0, 0, 24],
        padding: [12, 24],
      }),
      new MLDraftLink({
        isFilled: false,
        href: '#',
        linkType: 'third-party' as const,
        title: 'Только наши каналы',
        font: '700 20px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        background: 'rgba(47, 58, 244, 0.73)',
        borderRadius: [5],
        margin: [0, 12, 12],
        padding: [12, 24],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://www.youtube.com/c/pifagor1/live',
        linkType: 'third-party' as const,
        title: 'Группа ЕГЭ',
        font: '700 20px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        background: 'rgba(47, 58, 244, 0.73)',
        borderRadius: [5],
        margin: [0, 12, 12],
        padding: [12, 24],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://www.youtube.com/user/ShkolaPifagora',
        linkType: 'third-party' as const,
        title: 'Группа ОГЭ',
        font: '700 20px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        background: 'rgba(47, 58, 244, 0.73)',
        borderRadius: [5],
        margin: [0, 12, 12],
        padding: [12, 24],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 143,
        margin: [56, 116, 36],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Lex',
        font: '700 28px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 24],
        padding: [0, 40],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Болею за «Арсенал» уже больше 20 лет. Пишу про свои мысли про клуб, и не только. Веду паблик в вк, знаю о новостях «Арсенала» практически все. ',
        font: '700 20px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 60],
        padding: [0, 40],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com/arsscnews',
          'https://www.youtube.com/channel/UCBYo2XB0I9Q-EMdear8fD5w',
          'https://t.me/',
          'https://www.arsenal.com/',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 60],
        padding: [12, 12],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Поддержка через Donation:',
        font: '400 20px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 12],
        padding: [0, 24],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [0, 0, 6],
        padding: [0, 92],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Donation Alerts',
        fontSize: 18,
        fontWeight: 400,
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 24],
        padding: [0, 24],
      }),
    ],
  },
  {
    background: 'url(https://i.ibb.co/k6wzJxQ/background-9999-0.png)',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: 'https://i.ibb.co/HF1GpT7/logo-0-1.png',
        size: 175,
        padding: [56, 0, 40],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Eвгений',
        font: '700 26px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        textShadow: ['2px 1px 2px #0009'],
        background: 'rgba(47, 58, 244, 0.73)',
        margin: [0],
        padding: [12, 24, 0],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Основатель сервиса',
        font: '400 18px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        background: 'rgba(47, 58, 244, 0.73)',
        margin: [0, 0, 24],
        padding: [0, 24, 12],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://linkii.ru',
        linkType: 'third-party' as const,
        title: 'Материалы о проекте',
        font: '400 22px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        textShadow: ['2px 1px 2px #0009'],
        background: 'rgba(47, 58, 244, 0.73)',
        margin: [0, 0, 24],
        padding: [12, 24],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://linkii.ru',
        linkType: 'third-party' as const,
        title: 'Наш классический сайт',
        font: '400 22px Inter, sans-serif',
        textShadow: ['2px 1px 2px #0009'],
        textAlign: 'center',
        color: '#fff',
        background: 'rgba(47, 58, 244, 0.73)',
        margin: [0],
        padding: [12, 24],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [0, 0, 6],
        padding: [0, 16],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com/kracko23',
          'https://discordapp.com/users/534986739513819138/',
          'https://tlgg.ru/Evgeny163',
          'https://msng.link/o/?krasikov.evgeny=ig',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialService.DISCORD,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 60],
        padding: [12, 12],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 175,
        padding: [56, 0, 36],
      }),
      new MLDraftButton({
        isFilled: false,
        href: '',
        title: 'Забронировать столик',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        letterSpacing: 1,
        textShadow: ['2px 1px 2px #0009'],
        padding: [18, 24],
        margin: [0, 0, 24],
        background: '#E8A23999',
      }),
      new MLDraftButton({
        isFilled: false,
        href: '',
        title: 'Заказать доставку',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        letterSpacing: 1,
        textShadow: ['2px 1px 2px #0009'],
        padding: [18, 24],
        margin: [0, 0, 24],
        background: '#E8A23999',
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Контакты',
        font: '700 32px Inter, sans-serif',
        fontWeight: 700,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [12, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Адрес',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Советская ул., 74А, Тольятти',
        font: '16px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Время работы:',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Вс-Чт: 11.30-24.00\n\nПт-Сб: 11.30-2.00',
        font: '16px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Телефон',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: '+7 (848) 239-46-13',
        font: '16px Inter, sans-serif',
        fontWeight: 400,
        textAlign: 'left',
        color: '#fff',
        margin: [0],
        padding: [6, 24, 12],
      }),
      new MLDraftVote({
        isFilled: false,
        cells: [
          {
            order: 0,
            title: 'Как Вам бар?',
            value: 0,
          },
          {
            order: 1,
            title: 'Как Вам блюда?',
            value: 0,
          },
        ],
        titleBackground: '#E8A23999',
        font: '24px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        textShadow: ['2px 1px 2px #0009'],
        buttonBackground: '#E8A23999',
        buttonFont: '24px Inter, sans-serif',
        buttonLetterSpacing: 1,
        buttonTextShadow: ['2px 1px 2px #0009'],
        buttonTextAlign: 'center',
        margin: [0, 0, 60],
        padding: [18, 0],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://vk.com', 'https://youtube.com', 'https://t.me', 'https://instagram.com'],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 60],
        padding: [12, 12],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [56, 0, 36],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Руслан Утюг',
        font: '400 28px/1.4 Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 0],
        padding: [12, 24],
        background: '#E839CC99',
      }),
      new MLDraftText({
        isFilled: false,
        text: 'новая песня на площадках',
        font: '400 18px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 0],
        padding: [12, 24],
        background: '#E839CC99',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://vk.com', 'https://youtube.com', 'https://t.me', 'https://instagram.com'],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [39, 0, 33],
        padding: [0, 17],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://www.tiktok.com/',
          'https://www.twitch.tv/',
          'https://boosty.to/',
          'https://mail.google.com/mail/',
        ],
        linkTypes: [
          SocialNetwork.TIKTOK,
          SocialService.TWITCH,
          SocialService.BOOSTY,
          SocialNetwork.GMAIL,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'inside',
        margin: [20, 0, 0],
        padding: [0, 0],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'inside',
        margin: [20, 0, 0],
        padding: [0, 0],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://boom.ru/',
        linkType: 'third-party' as const,
        title: 'Слушай в ВООМ',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E839CC99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://vk.com/audio',
        linkType: 'third-party' as const,
        title: 'Слушай в VK',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E839CC99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://open.spotify.com/',
        linkType: 'third-party' as const,
        title: 'Слушай в Spotify',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E839CC99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.yandex.by/home',
        linkType: 'third-party' as const,
        title: 'Слушай в Яндекс',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#FFFBFB',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [50, 15, 15, 50],
        background: '#E839CC99',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com',
          'https://youtube.com',
          'https://www.tiktok.com/',
          'https://instagram.com',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TIKTOK,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [55, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // LesaFS
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [56, 0, 36],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Lesa FS',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 0],
        padding: [38.5, 24],
        background: '#E839CC99',
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        href: 'https://share.boom.ru/album/20152494/?share_auth=023985e6644b5c9a66811a629924d0',
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [12, 24],
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        href: 'https://music.yandex.ru/album/22583577',
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [12, 55],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com/lesafs',
          'https://vk.com/lesa_fs',
          'https://t.me/lesa_fs_music',
          'https://instagram.com/lesa_fs',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.VK,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // CatsBackground
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [5, 0, 0],
        margin: [0, 0, 24],
      }),
      new MLDraftButton({
        isFilled: false,
        href: '',
        title: 'Стрижка - 500р',
        font: '24px Inter, sans-serif',
        fontWeight: 400,
        color: '#fff',
        letterSpacing: 1,
        textShadow: ['2px 1px 2px #0009'],
        padding: [20, 24],
        borderRadius: [15],
        margin: [0, 0, 12],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftButton({
        isFilled: false,
        href: '',
        title: 'Записаться на стрижку',
        font: '24px Inter, sans-serif',
        color: '#fff',
        letterSpacing: 1,
        textShadow: ['2px 1px 2px #0009'],
        padding: [20, 24],
        borderRadius: [15],
        margin: [0, 0, 15],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftWidget({
        isFilled: true,
        url: 'https://widget.qiwi.com/widgets/middle-widget-300x300?publicKey=48e7qUxn9T7RyYE1MVZswX1FRSbE6iyCj2gCRwwF3Dnh5XrasNTx3BGPiMsyXQFNKQhvukniQG8RTVhYm3iPsXMCEHsEfvcM9fWDrHZGpWKAFeZPjiJbFtPjyxAanWqYMcU9DSN7wMpc8VGAVjmd9yjdSQRA92xGdkxFbtNyRSzFPrYeoktJhC8rNxvbe',
        width: 300,
        height: 300,
        margin: [0, 0, 12],
        padding: [0, 12],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com',
          'https://t.me',
          'https://instagram.com',
          'https://www.whatsapp.com/',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.TELEGRAM,
          SocialNetwork.WHATSAPP,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // rescueFund
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        margin: [0, 0, 24],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Фонд "Спасение"',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 16],
        padding: [20, 24],
        background: 'rgba(57,95,232,0.6)',
      }),
      new MLDraftButton({
        isFilled: false,
        href: '',
        title: 'Оплатить',
        font: '24px Inter, sans-serif',
        color: '#fff',
        letterSpacing: 1,
        textShadow: ['2px 1px 2px #0009'],
        padding: [15, 24],
        borderRadius: [51],
        margin: [0, 21, 15],
        background: 'rgb(49,255,0)',
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'outside',
        margin: [12, 24],
        padding: [0, 16, 5],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com',
          'https://t.me',
          'https://www.patreon.com/',
          'https://instagram.com',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialService.BOOSTY,
          SocialService.PATREON,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // vikinG
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
      }),
      new MLDraftText({
        isFilled: false,
        text: 'VikinG Обучение IТату в Тольятти',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 16],
        padding: [20, 24],
        background: '#E8394E99',
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'inside',
        margin: [12, 24],
        padding: [20, 16],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://vk.com', 'https://youtube.com', 'https://t.me', 'https://instagram.com'],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // lesa
      new MLDraftImage({
        isFilled: false,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'outside',
        padding: [56, 0, 36],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.apple.com/ru/album/1630423033?at=1000lvHr',
        linkType: 'third-party' as const,
        title: 'Apple Music',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.yandex.ru/album/22778461',
        linkType: 'third-party' as const,
        title: 'Слушай в Яндекс',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#FFFBFB',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://share.boom.ru/album/20367095?share_auth=023d3b0f48b141abce811a62be0ed0',
        linkType: 'third-party' as const,
        title: 'Слушай в VK',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://accounts.spotify.com/login?continue=https%3A%2F%2Fopen.spotify.com%2Falbum%2F74pr8sjT3iAutMvyGj9OJF',
        linkType: 'third-party' as const,
        title: 'Слушай в Spotify',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.apple.com/ru/album/1630423033?at=1000lvHr',
        linkType: 'third-party' as const,
        title: 'В iTunes',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://zvuk.com/release/24523908',
        linkType: 'third-party' as const,
        title: 'Слушай на Звук',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.youtube.com/playlist?list=OLAK5uy_mcLnULIsKyuVo8nG5C7BH2cunCluGShus&feature=share',
        linkType: 'third-party' as const,
        title: 'YouTube Music',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#FFFBFB',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://ok.ru/music/album/122937016505133',
        linkType: 'third-party' as const,
        title: 'Одноклассники',
        textAlign: 'center',
        font: '24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 32],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(232,57,204,0.6)',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com/lesafs',
          'https://vk.com/lesa_fs',
          'https://t.me/lesa_fs_music',
          'https://instagram.com/lesa_fs',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.VK,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 67,
        margin: [35, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // Ulyashchinkov
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [6, 0, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Ульященков Сергей',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        padding: [16, 24],
        background: '#E8A23999',
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Уже больше 20лет я помогаю компаниям и стартапам',
        font: '400 16px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        padding: [12, 24],
        background: '#E8A23999',
      }),
      new MLDraftImage({
        isFilled: true,
        image: null,
        imgPosition: 'bottom',
        textPosition: 'inside',
        padding: [39, 0, 20],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://zen.yandex.ru/', 'https://vk.com', 'https://t.me'],
        linkTypes: [
          SocialService.DZEN,
          SocialNetwork.VK,
          SocialService.ARTOFDIGITAL,
          SocialNetwork.TELEGRAM,
        ],
        size: 65,
        margin: [35, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // andreyYurchenkov
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [56, 0, 36],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Андрей Юрченков',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 0],
        padding: [12, 24],
        background: '#E8394E99',
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Основатель музыкальной онлайн школы "Путь Музыканта"',
        font: '400 18px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 0],
        padding: [12, 24],
        background: '#E8394E99',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://vk.com', 'https://youtube.com', 'https://t.me', 'https://instagram.com'],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [39, 0, 33],
        padding: [0, 17],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://www.tiktok.com/',
          'https://www.twitch.tv/',
          'https://boosty.to/',
          'https://mail.google.com/mail/',
        ],
        linkTypes: [
          SocialNetwork.TIKTOK,
          SocialService.TWITCH,
          SocialService.BOOSTY,
          SocialNetwork.GMAIL,
        ],
        size: 65,
        margin: [0, 0, 425],
        padding: [0, 17],
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://boom.ru/',
        linkType: 'third-party' as const,
        title: 'Слушай в ВООМ',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E8394E99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://vk.com/audio',
        linkType: 'third-party' as const,
        title: 'Слушай в VK',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E8394E99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://open.spotify.com/',
        linkType: 'third-party' as const,
        title: 'Слушай в Spotify',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [15],
        background: '#E8394E99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://music.yandex.by/home',
        linkType: 'third-party' as const,
        title: 'Слушай в Яндекс',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#FFFBFB',
        padding: [24, 24],
        margin: [0, 24, 12],
        borderRadius: [50, 15, 15, 50],
        background: '#E8394E99',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://vk.com',
          'https://youtube.com',
          'https://www.tiktok.com/',
          'https://instagram.com',
        ],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TIKTOK,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [55, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // deadp47
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 154,
        padding: [36, 0, 6],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'DeadP47',
        font: '400 22px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0],
        padding: [22, 24, 12],
        background: 'rgba(232, 57, 204, 0.6)',
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Пивные аниме стримы по пятницам',
        font: '400 18px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0],
        padding: [12, 24, 32],
        background: 'rgba(232, 57, 204, 0.6)',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://vk.com', 'https://youtube.com', 'https://t.me', 'https://instagram.com'],
        linkTypes: [
          SocialNetwork.VK,
          SocialNetwork.YOUTUBE,
          SocialNetwork.TELEGRAM,
          SocialNetwork.INSTAGRAM,
        ],
        size: 65,
        margin: [39, 0, 33],
        padding: [0, 17],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'https://www.tiktok.com/',
          'https://wasd.tv/',
          'https://discord.com/',
          'https://www.twitch.tv/',
        ],
        linkTypes: [
          SocialNetwork.TIKTOK,
          SocialService.WASD,
          SocialService.DISCORD,
          SocialService.TWITCH,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
      new MLDraftText({
        isFilled: true,
        text: 'На жизнь за границей',
        textAlign: 'center',
        font: '400 24px Inter, sans-serif',
        color: '#FEF9F9',
        margin: [18, 0, 0, 0],
        padding: [0, 0],
      }),
      new MLDraftText({
        isFilled: true,
        text: '1',
        color: 'rgba(254, 21, 217, 0)',
        background: 'rgba(254, 21, 217, 0.85)',
        margin: [0, 92, 0, 0],
        padding: [8, 0],
      }),
      new MLDraftText({
        isFilled: true,
        text: '1',
        color: 'rgba(102, 82, 99, 0)',
        background: 'rgba(102, 82, 99, 0.6)',
        margin: [-35.2, 0, 0, 283],
        padding: [8, 0],
      }),
      new MLDraftText({
        isFilled: true,
        text: '0',
        font: '400 22px Inter, sans-serif',
        color: '#FEF9F9',
        margin: [0, 0, 0, 0],
        padding: [0, 0],
      }),
      new MLDraftText({
        isFilled: true,
        text: '200 000',
        color: '#FEF9F9',
        font: '400 22px Inter, sans-serif',
        margin: [-27, 0, 0, 280],
        padding: [0, 0],
      }),
      new MLDraftSocial({
        isFilled: false,
        links: ['https://boosty.to/', 'https://www.patreon.com/', 'https://www.twitch.tv/'],
        linkTypes: [SocialService.BOOSTY, SocialService.PATREON, SocialService.DONATIONALERTS],
        size: 65,
        margin: [5, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      // wearearsenal
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 110,
        margin: [0, 0, 24, 0],
        padding: [16, 0, 0, 0],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'Арсенал - We Are The Arsenal',
        font: '400 36px Inter, sans-serif',
        color: '#fff',
        textAlign: 'center',
        margin: [0, 0, 0, 0],
        padding: [12, 24],
        background: '#E8394E99',
      }),
      new MLDraftText({
        isFilled: false,
        text: `Авторский проект про Арсенал\n\nПодкасты, новости и переводы`,
        font: '700 16px Inter, sans-serif',
        textAlign: 'center',
        color: '#fff',
        margin: [0, 0, 0, 0],
        padding: [8, 24],
        background: '#E8394E99',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://www.youtube.com/channel/UCJA2ybVcB9DjOr66E8Lpp-g',
        linkType: 'third-party' as const,
        title: 'Наш Youtube канал',
        textAlign: 'center',
        font: '700 20px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24, 24, 24],
        margin: [33, 24, 28, 24],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(133, 164, 204, 0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://vk.com/wearethearsenal',
        linkType: 'third-party' as const,
        title: 'Главный фанатский паблик в ВК',
        textAlign: 'center',
        font: '700 20px Inter, sans-serif',
        color: '#fff',
        padding: [10, 24, 10, 24],
        margin: [0, 24, 28, 24],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(133, 164, 204, 0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://boosty.to/asan1886',
        linkType: 'third-party' as const,
        title: 'Поддержка проекта',
        textAlign: 'center',
        font: '700 20px Inter, sans-serif',
        color: '#fff',
        padding: [10, 24, 10, 24],
        margin: [0, 24, 12, 24],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(133, 164, 204, 0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://t.me/abibyllaev',
        linkType: 'third-party' as const,
        title: 'Канал про Арсенал',
        textAlign: 'center',
        font: '700 20px Inter, sans-serif',
        color: '#fff',
        padding: [24, 24, 24, 24],
        margin: [0, 24, 28, 24],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(133, 164, 204, 0.6)',
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'https://vk.com/arsenalkurilka',
        linkType: 'third-party' as const,
        title: 'Мемный паблик',
        textAlign: 'center',
        font: '700 20px Inter, sans-serif',
        color: '#fff',
        padding: [10, 24, 10, 24],
        margin: [0, 24, 28, 24],
        borderRadius: [50, 15, 15, 50],
        background: 'rgba(133, 164, 204, 0.6)',
      }),
    ],
  },
  {
    background: '#fff',
    blocks: [
      new MLDraftLogo({
        isFilled: true,
        logo: '',
        size: 161,
        margin: [0, 0, 24],
      }),
      new MLDraftText({
        isFilled: false,
        text: 'ROMA FOBI',
        font: '700 24px Inter, sans-serif',
        textAlign: 'center',
        padding: [15, 24],
        borderRadius: [51],
        margin: [0, 21, 15],
        background: 'rgb(4,253,75)',
      }),
      new MLDraftCarousel({
        isFilled: false,
        dots: false,
        arrows: false,
        images: [sliderImage1, sliderImage2, sliderImage3],
        interval: 3000,
        itemsPerView: 1,
      }),
      new MLDraftLink({
        isFilled: false,
        href: 'http://www.tiktok.com/@roma_fobi',
        linkType: 'third-party' as const,
        title: 'TIK TOK',
        image: 'https://i.ibb.co/JjbzXnk/svgIcon1.png',
        textAlign: 'center',
        font: '700 22px Inter, sans-serif',
        padding: [15, 24],
        borderRadius: [51],
        margin: [0, 21, 15],
        background: 'rgb(4,253,75)',
      }),
      new MLDraftSocial({
        isFilled: false,
        links: [
          'notofficial777@mail.ru',
          'http://www.tiktok.com/@roma_fobi',
          'https://vc.ru/u/1137112-roma-fobi',
          'https://www.instagram.com/roma_fobi',
        ],
        linkTypes: [
          SocialService.GMAIL,
          SocialNetwork.TIKTOK,
          SocialService.TELEGRAM,
          SocialService.INSTAGRAM,
        ],
        size: 65,
        margin: [0, 0, 0],
        padding: [0, 17],
      }),
    ],
  },
] as const;
